### PR TITLE
Error in graph

### PR DESCRIPTION
**Pull request by WhiteHatArpit**
#28

### CODE REVIEW

**Comment by ketanbhatt** [comment]
@TigerApps I think you did it from the same branch so all commits are here now

**Comment by WhiteHatArpit** [comment]
yep. Merge both. Will get forwarded.

**Comment by ketanbhatt** [comment]
@TigerApps dont do this in future bro, gives me a headache

**Comment by WhiteHatArpit** [comment]
Cool!

**Pull request merged**
